name: Unit Tests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - if: ${{ hashFiles('apps/mobile/pubspec.yaml') != '' }}
        working-directory: apps/mobile
        run: flutter test
